# LastSignal Configuration Example
# Copy this file to ~/.lastsignal/config.toml and modify as needed

[checkin]
# Duration to wait after a checkin before asking for another checkin
# Supports: s/seconds, m/minutes, h/hours, d/days
# Examples: "30s", "5m", "2h", "7d", "1day", "24hours"
duration_between_checkins = "7d"

# Time to wait between each output attempt if no response
# Examples: "30m", "2h", "1d"
output_retry_delay = "24h"

# Outputs to use for checkin requests (in order of preference)
# The system will try each output until one succeeds or all fail

# Example: Facebook Messenger output for admin checkin
[[checkin.outputs]]
type = "facebook_messenger"
config = { user_id = "your_admin_facebook_user_id", access_token = "your_facebook_page_access_token" }

# Example: Email output for admin checkin (Gmail)
[[checkin.outputs]]
type = "email"
config = { 
    to = "admin@example.com", 
    smtp_host = "smtp.gmail.com", 
    smtp_port = "587", 
    username = "sender@gmail.com", 
    password = "your_app_password"
}

[recipient]
# Duration after no admin checkin to fire the last signal
# Examples: "2 weeks" would be "14d", "1 month" would be "30d"
duration_before_last_signal = "14d"

# Time to wait between each output attempt if no response
# Examples: "30m", "6h", "1d"  
output_retry_delay = "12h"

# Outputs to use for last signal (in order of preference)
# These are the emergency contacts who will receive the last signal

# Example: Facebook Messenger to emergency contact
[[recipient.last_signal_outputs]]
type = "facebook_messenger" 
config = { user_id = "emergency_contact_facebook_id", access_token = "your_facebook_page_access_token" }

# Example: Email to emergency contact
[[recipient.last_signal_outputs]]
type = "email"
config = { 
    to = "emergency@example.com", 
    smtp_host = "smtp.gmail.com", 
    smtp_port = "587", 
    username = "sender@gmail.com", 
    password = "your_app_password" 
}

# Example: Email to multiple emergency contacts
[[recipient.last_signal_outputs]]
type = "email"
config = { 
    to = "family@example.com", 
    smtp_host = "smtp.gmail.com", 
    smtp_port = "587", 
    username = "sender@gmail.com", 
    password = "your_app_password" 
}

[last_signal]
# Type of adapter to use for generating the last signal message
adapter_type = "file"

# Path to the message file (relative to data directory or absolute)
message_file = "last_signal_message.txt"

[app]
# Directory to store state and logs (defaults to ~/.lastsignal/)
data_directory = "~/.lastsignal/"

# Log level: trace, debug, info, warn, error
log_level = "info"