# LastSignal Configuration Example
# Copy this file to ~/.lastsignal/config.toml and modify as needed

[checkin]
# Duration to wait after a checkin before asking for another checkin
# Supports: s/seconds, m/minutes, h/hours, d/days
# Examples: "30s", "5m", "2h", "7d", "1day", "24hours"
duration_between_checkins = "7d"

# Time to wait between each output attempt if no response
# Examples: "30m", "2h", "1d"
output_retry_delay = "24h"

# Outputs to use for checkin requests (in order of preference)
# The system will try each output until one succeeds or all fail



# Example: WHOOP device activity monitoring for automatic checkin
# This adapter checks if there's been recent device activity (sleep, recovery, cycle data)
# and treats it as an automatic checkin response
[[checkin.outputs]]
type = "whoop"
bidirectional = true
config = { 
    access_token = "your_whoop_access_token",
    max_hours_since_activity = "24"  # Consider alive if activity within 24 hours
}
# Example: Email output for admin checkin (Gmail)
[[checkin.outputs]]
type = "email"
config = { 
    to = "admin@example.com", 
    smtp_host = "smtp.gmail.com", 
    smtp_port = "587", 
    username = "sender@gmail.com", 
    password = "your_app_password"
}

[recipient]
# Maximum time since last successful checkin before firing emergency message
# Examples: "2 weeks" would be "14d", "1 month" would be "30d"
max_time_since_last_checkin = "14d"

# Time to wait between each output attempt if no response
# Examples: "30m", "6h", "1d"  
output_retry_delay = "12h"

# Outputs to use for last signal (in order of preference)
# These are the emergency contacts who will receive the last signal

# Example: Email to emergency contact
[[recipient.last_signal_outputs]]
type = "email"
config = { 
    to = "emergency@example.com", 
    smtp_host = "smtp.gmail.com", 
    smtp_port = "587", 
    username = "sender@gmail.com", 
    password = "your_app_password" 
}

# Example: Email to multiple emergency contacts
[[recipient.last_signal_outputs]]
type = "email"
config = { 
    to = "family@example.com", 
    smtp_host = "smtp.gmail.com", 
    smtp_port = "587", 
    username = "sender@gmail.com", 
    password = "your_app_password" 
}

[last_signal]
# Type of adapter to use for generating the last signal message
adapter_type = "file"

# Path to the message file (relative to data directory or absolute)
message_file = "last_signal_message.txt"

[app]
# Directory to store state and logs (defaults to ~/.lastsignal/)
data_directory = "~/.lastsignal/"

# Log level: trace, debug, info, warn, error
log_level = "info"
